### ISSUE TITLE
Restoring process fails due to cgroup: Can't mount. Resource busy.

### ISSUE THREAD

**Issue by xaviermerino** [checkpoint-restore/criu#453] opened 2018-03-14 23:17 UTC
Hello,

In my tests, I am using a simple application that prints factorials for eternity. It successfully checkpointed and I am able to restore on the same host no problem. Whenever I attempt to restore on another host i get the following error: 

```
(00.001245) cpu: fpu:1 fxsr:1 xsave:1
(00.001315) kernel pid_max=131072
(00.001322) Reading image tree
(00.001351) Add mnt ns 12 pid 1
(00.001363) pstree pid_max=1
(00.001372) Will restore in 6c020000 namespaces
(00.001375) NS mask to use 6c020000
(00.001380) Collecting 37/54 (flags 2)
(00.001396) Collected [usr/bin/python2.7] ID 0x1
(00.001404) Collected [lib/arm-linux-gnueabihf/libm-2.23.so] ID 0x2
(00.001409) Collected [lib/arm-linux-gnueabihf/libz.so.1.2.8] ID 0x3
(00.001413) Collected [lib/arm-linux-gnueabihf/libutil-2.23.so] ID 0x4
(00.001418) Collected [lib/arm-linux-gnueabihf/libdl-2.23.so] ID 0x5
(00.001422) Collected [lib/arm-linux-gnueabihf/libc-2.23.so] ID 0x6
(00.001426) Collected [lib/arm-linux-gnueabihf/libpthread-2.23.so] ID 0x7
(00.001433) Collected [lib/arm-linux-gnueabihf/ld-2.23.so] ID 0x8
(00.001438) Collected pipe entry ID 0x9 PIPE ID 0x1a640
(00.001447) Found id pipe:[108096] (fd 0) in inherit fd list
(00.001452) Collected pipe entry ID 0xa PIPE ID 0x1a641
(00.001456) Found id pipe:[108097] (fd 1) in inherit fd list
(00.001460) Collected pipe entry ID 0xb PIPE ID 0x1a642
(00.001464) Found id pipe:[108098] (fd 2) in inherit fd list
(00.001468) Collected [.] ID 0xc
(00.001475)  `- ... done
(00.001478) Collecting 43/59 (flags 0)
(00.001484) No remap-fpath.img image
(00.001488)  `- ... done
(00.001530) cg: rewriting factorial to /factorial2
(00.001540) cg: rewriting factorial to /factorial2
(00.001545) cg: rewriting user.slice/factorial to /user.slice/factorial2
(00.001549) cg: rewriting factorial to /factorial2
(00.001554) cg: rewriting user.slice/factorial to /user.slice/factorial2
(00.001558) cg: rewriting user.slice/user-1000.slice/session-c11.scope/factorial to /user.slice/user-1000.slice/session-c2.scope/factorial2
(00.001564) cg: Preparing cgroups yard (cgroups restore mode 0x4)
(00.003087) cg: Opening .criu.cgyard.BFjUMG as cg yard
(00.003123) cg: 	Making controller dir .criu.cgyard.BFjUMG/cpuset (cpuset)
(00.004366) cg: Determined cgroup dir cpuset//factorial2 already exist
(00.004385) cg: Skip restoring properties on cgroup dir cpuset//factorial2
(00.004412) cg: 	Making controller dir .criu.cgyard.BFjUMG/net_cls (net_cls)
(00.004602) Error (criu/cgroup.c:1700): cg: 	Can't mount controller dir .criu.cgyard.BFjUMG/net_cls: Device or resource busy
```

I am restoring like this:

```
sudo runc restore --image-path ./image --work-path ./work --bundle ./ factorial
```
I don't know if the problem is because the two hosts have different kernel versions. The original host has kernel `4.9.80-v7+` while the other host I am attempting to restore into has kernel `4.13.0-37-generic`.

Is there something I am missing? I am attaching the dump and restore logs. 

[dump.log.txt](https://github.com/checkpoint-restore/criu/files/1813452/dump.log.txt)
[restore.log.txt](https://github.com/checkpoint-restore/criu/files/1813456/restore.log.txt)

**Comment by avagin** [comment] 2018-03-14 23:25
Could you show output for "cat /proc/self/cgroup" from this host?

**Comment by xaviermerino** [comment] 2018-03-14 23:34
From the original host (the one who started the application):
```
7:cpuset:/
6:net_cls:/
5:blkio:/user.slice
4:freezer:/
3:cpu,cpuacct:/user.slice
2:devices:/user.slice
1:name=systemd:/user.slice/user-1000.slice/session-c14.scope
```
From the host that I want to restore onto: 

```
12:freezer:/
11:devices:/user.slice
10:memory:/user.slice
9:rdma:/
8:pids:/user.slice/user-1000.slice
7:blkio:/user.slice
6:perf_event:/
5:net_cls,net_prio:/
4:hugetlb:/
3:cpu,cpuacct:/user.slice
2:cpuset:/
1:name=systemd:/user.slice/user-1000.slice/session-c2.scope
```

**Comment by avagin** [comment] 2018-03-15 00:01
The problem is that net_cls is mounted together with net_prio on the second host.

```
6:net_cls:/
```

```
5:net_cls,net_prio:/
```

**Comment by avagin** [comment] 2018-03-15 00:16
You can modify cgroup.img with help of the crit tool.

For that, you need to decode an image file into a json format
```
crit decode --pretty -i cgroup.img  > cgroup.json
```

Then you need to apply this patch to cgroup.json
```
@@ -1142,7 +1142,8 @@
                 }, 
                 {
                     "cnames": [
-                        "net_cls"
+                        "net_cls", 
+                        "net_prio"
                     ], 
                     "dirs": [
                         {
```

And encode cgroup.json back into the criu format:
```
crit decode  -o cgroup.img  < cgroup.json
```

**Comment by xaviermerino** [comment] 2018-03-15 04:49
Thanks. That seemed to get me through the `net_cls` error. Restore now fails because it is missing a mapping. 

```
(00.019048) Error (criu/mount.c:2531): mnt: No mapping for /sys/fs/cgroup/net_cls mountpoint
(00.023067) Error (criu/mount.c:2991): mnt: Can't remove the directory /tmp/.criu.mntns.UIinoj: No such file or directory
```
The restore did progress further though. I am attaching the [restore log](https://github.com/checkpoint-restore/criu/files/1814004/restore.log.txt).

**Comment by avagin** [comment] 2018-03-15 04:59
This error has the same reason and it can be fixed by the same way.

You need to decode a mountpoints image
```
crit decode --pretty -i mountpoints-X.img -o mountpoints-X.json
```

Then remove a net_cls mount point from it.

and decode mountpoints-X.json back to the criu format

```
crit encode -i mountpoints-X.json -o mountpoints-X.img
```

**Comment by xaviermerino** [comment] 2018-03-15 05:14
That did fix the error I was having. And now I am out of the cgroups errors. Thanks. 
The only problem that I'm having now is a core mismatch.

```
(00.013005) Error (criu/cr-restore.c:1003): Core march mismatch 2
(00.028540) Error (criu/mount.c:2991): mnt: Can't remove the directory /tmp/.criu.mntns.eXLOt3: No such file or directory
(00.028630) Error (criu/cr-restore.c:2174): Restoring FAILED.
```
Do you know what this means?

**Comment by avagin** [comment] 2018-03-15 05:20
CORE_ENTRY__MARCH__ARM = 2

**Comment by avagin** [comment] 2018-03-15 05:21
Could you show /proc/cpuinfo for both hosts? What are criu versions on these hosts?

**Comment by xaviermerino** [comment] 2018-03-15 05:36
I figured it had something to do with the architecture. I am attempting to have an ARM container moved into an x86 machine using qemu as a translation layer. Both hosts have CRIU version 3.7. 

The original host is a Raspberry Pi 3. In order to get it working I followed the steps in #446. This is the cpuinfo.

```
pi@raspberrypi:~ $ cat /proc/cpuinfo
processor	: 0
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 1
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 2
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 3
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

Hardware	: BCM2835
Revision	: a02082
Serial		: 000000007b7a8c5e
```
The other host is a VM running on a MacBook Pro. It's cpuinfo is below:

```
xaviermerino@zfs-1:~/Documents/factorial$ cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
stepping	: 9
microcode	: 0x15
cpu MHz		: 2594.171
cache size	: 6144 KB
physical id	: 0
siblings	: 3
core id		: 0
cpu cores	: 3
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cpuid_fault pti retpoline fsgsbase tsc_adjust smep arat
bugs		: cpu_meltdown spectre_v1 spectre_v2
bogomips	: 5188.34
clflush size	: 64
cache_alignment	: 64
address sizes	: 43 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
stepping	: 9
microcode	: 0x15
cpu MHz		: 2594.171
cache size	: 6144 KB
physical id	: 0
siblings	: 3
core id		: 1
cpu cores	: 3
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cpuid_fault pti retpoline fsgsbase tsc_adjust smep arat
bugs		: cpu_meltdown spectre_v1 spectre_v2
bogomips	: 5188.34
clflush size	: 64
cache_alignment	: 64
address sizes	: 43 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
stepping	: 9
microcode	: 0x15
cpu MHz		: 2594.171
cache size	: 6144 KB
physical id	: 0
siblings	: 3
core id		: 2
cpu cores	: 3
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cpuid_fault pti retpoline fsgsbase tsc_adjust smep arat
bugs		: cpu_meltdown spectre_v1 spectre_v2
bogomips	: 5188.34
clflush size	: 64
cache_alignment	: 64
address sizes	: 43 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
stepping	: 9
microcode	: 0x15
cpu MHz		: 2594.171
cache size	: 6144 KB
physical id	: 1
siblings	: 3
core id		: 0
cpu cores	: 3
apicid		: 4
initial apicid	: 4
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cpuid_fault pti retpoline fsgsbase tsc_adjust smep arat
bugs		: cpu_meltdown spectre_v1 spectre_v2
bogomips	: 5188.34
clflush size	: 64
cache_alignment	: 64
address sizes	: 43 bits physical, 48 bits virtual
power management:

processor	: 4
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
stepping	: 9
microcode	: 0x15
cpu MHz		: 2594.171
cache size	: 6144 KB
physical id	: 1
siblings	: 3
core id		: 1
cpu cores	: 3
apicid		: 5
initial apicid	: 5
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cpuid_fault pti retpoline fsgsbase tsc_adjust smep arat
bugs		: cpu_meltdown spectre_v1 spectre_v2
bogomips	: 5188.34
clflush size	: 64
cache_alignment	: 64
address sizes	: 43 bits physical, 48 bits virtual
power management:

processor	: 5
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
stepping	: 9
microcode	: 0x15
cpu MHz		: 2594.171
cache size	: 6144 KB
physical id	: 1
siblings	: 3
core id		: 2
cpu cores	: 3
apicid		: 6
initial apicid	: 6
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cpuid_fault pti retpoline fsgsbase tsc_adjust smep arat
bugs		: cpu_meltdown spectre_v1 spectre_v2
bogomips	: 5188.34
clflush size	: 64
cache_alignment	: 64
address sizes	: 43 bits physical, 48 bits virtual
power management:

```
I can run an ARM container on my x86 machine no problem. I was just trying to restore one now.

**Comment by avagin** [comment] 2018-03-15 06:17
In this case, you need to compile criu for arm and run it via qemu on x86 too. I am not sure that this will work, but it is worth to try.

**Comment by avagin** [comment] 2018-03-15 06:31
I think we can close this issue. You always can open another one.

**Comment by avagin** [comment] 2018-03-15 17:58
> In this case, you need to compile criu for arm and run it via qemu on x86 too. I am not sure that this will work, but it is worth to try.

I have understood that this will not work too. When you use qemu-user to run arm binaries, a process runs  qemu-user code which translates arm instructions into x86_64 instructions.

For example, you can see qemu-user mappings in a process:
```
[root@fc24 ~]# ps -fp 1583
UID        PID  PPID  C STIME TTY          TIME CMD
root      1583  1019 39 20:53 ?        00:00:17 /usr/bin/qemu-arm-static /usr/bin/apt-get install -y build-essential protobuf-c-compiler libprotobuf-c0-dev libprotobuf-dev bsdmainutils proto
[root@fc24 ~]# cat /proc/1583/maps  | grep qemu
60000000-602d3000 r-xp 00000000 fd:02 214313                             /usr/bin/qemu-arm-static
604d2000-604dd000 rw-p 002d2000 fd:02 214313                             /usr/bin/qemu-arm-static
```

CRIU knows nothing about qemu-user, so "criu restore" will restore a process without qemu-user.

**Comment by 0x7f454c46** [comment] 2018-03-15 18:03
Oh, that may be another awesome feature - to deal with qemu-user migration.
But I'm not sure it's possible at all without patching qemu, because if we mmap() qemu binary inside process - it'll not know anything about running process :(
So, it looks as a big amount of work. Without a customer, no one will have the motivation to do it.

**Comment by xaviermerino** [comment] 2018-03-15 19:32
@avagin @0x7f454c46 I am actually interested in implementing this. This will allow cross-architecture migration which sounds really cool to me.

**Closed** 2018-03-17 04:24 UTC
Labels: question
