### ISSUE TITLE
Stale RA-derived IPv6 default route stuck in the routing table after live migration

### ISSUE THREAD

**Issue by ayourtch** [checkpoint-restore/criu#177] opened 2016-06-22 13:59 UTC
This looks to me a bug in iproute2 save/restore code, but I am opening an issue here to discuss the best approach, since the iproute2 fix might not be trivial logistically.

iproute2 save/restore does not dump the lifetimes of the routes.  As a result, the default IPv6 route which is derived from IPv6 Router Advertisements, gets restored upon migration as static, and the kernel never times it out.

Normally a container will use the NUD (neighbor unreachability detection) so the correct router will be selected. However, upon the migration back the stale route seems to inhibit the container from acquiring the address using SLAAC (stateless address autoconfiguration).

Short of making the iproute2 save/restore the lifetimes as well, there are two approaches:

1) after restoring the routes upon migration, delete the default routes manually and issue a router solicitation

2) try to edit the contents of the dump generated by "ip route save" and cut out the default route from there, then issue a router solicitation upon the restore.

What do you think ?

The issue is easily reproducible on both lxc and lxd containers configured with IPv6 and SLAAC addressing within the container...

**Comment by tych0** [comment] 2016-06-22 14:08
On Wed, Jun 22, 2016 at 06:59:16AM -0700, Andrew Yourtchenko wrote:
> This looks to me a bug in iproute2 save/restore code, but I am opening an issue here to discuss the best approach, since the iproute2 fix might not be trivial logistically.
> 
> iproute2 save/restore does not dump the lifetimes of the routes.  As a result, the default IPv6 route which is derived from IPv6 Router Advertisements, gets restored upon migration as static, and the kernel never times it out.
> 
> Normally a container will use the NUD (neighbor unreachability detection) so the correct router will be selected. However, upon the migration back the stale route seems to inhibit the container from acquiring the address using SLAAC (stateless address autoconfiguration).
> 
> Short of making the iproute2 save/restore the lifetimes as well, there are two approaches:
> 
> 1) after restoring the routes upon migration, delete the default routes manually and issue a router solicitation
> 
> 2) try to edit the contents of the dump generated by "ip route save" and cut out the default route from there, then issue a router solicitation upon the restore.
> 
> What do you think ?
> 
> The issue is easily reproducible on both lxc and lxd containers configured with IPv6 and SLAAC addressing within the container...

I can confirm this bug, although I'm not familiar with ipv6 to really
understand how to fix it. I'm happy to help writing patches once we
figure out the best way, though.

Is there any reason you think that fixing it in iproute2 would be
particularly hard? If we can get patches accepted upstream, I can get
them distro-patched into Ubuntu Xenial.

**Comment by ayourtch** [comment] 2016-06-22 15:58
The reason I think it is trickier to deal with this via iproute2 is that it's the netlink message that is missing the attributes, thus any potential patch would need both kernel and userland modifications, I think that would take quite some time ? Also, I am not sure myself what the correct behavior in this case is... I can successfully convince myself in either restoring the route with a timer or not saving a temporary route at all... :)

I will toy a bit in my lab with option (1), and see how it works... Option (2) probably is too convoluted/tightly coupled to iproute2, what do you think ?

**Comment by xemul** [comment] 2016-06-28 10:32
@ayourtch , do I get you right, that there's currently no way to tell temporary routes from static ones in ip r l output?

**Comment by ayourtch** [comment] 2016-06-28 12:16
No, actually the restored routes are marked as derived from RA, but they do not have the remaining lifetime - so they get stuck forever.

In the lab I've for now I am testing a patched version of criu what calls a callback after the restore which cleans up the offending route, in this fashion:

`ip -6 route | grep -v expires | grep default | sed -e 's/linkdown//g' | xargs -L 1 ip -6 route del`

But in general just deleting the route will be a problem if there are packets in flight in either direction - since then the OS will get an error back and the sockets will close, so I will experiment with a temporary blackhole default route of a smaller preference that gets added before the dump and removed after the end of the dump and restore.

**Comment by avagin** [comment] 2016-06-29 01:18
The problem is in the kernel. Ussually the format of netlink packages are symetric, I mean that if we request all routes for one namespace and send them back from another clean namespace, the second namespace will have the same set of routes. It's what ip save/restore commands do.

But here is the RTA_EXPIRES attribute, which is used to set a timeout, but the current timeout is shown in the RTA_CACHEINFO attribute. It's a reason of this problem. We can workaround it from user-space.

Is here only a problem with restoring timeouts? Or maybe we always need to remove RA-derived IPv6 routes?

**Comment by ayourtch** [comment] 2016-07-07 11:28
Sorry for the delay with the reply - took some time to build the harness that fixes up the routing during the live migration, to do more testing "in vivo".

@avagin Restoring the timeouts would work, to some extent. During the interface bring-up after the restore, the host apparently sends Router Solicitation, which gets it to learn the new router - then it will have two of them for some time, and then Neighbor Unreachability Detection mechanism should take care of detecting the dead one. Still would not be optimal, since it can take some time.

I've decided to test the idea with deleting the RA-derived routes, and copypasted some existing code around to run a custom hook, like this: http://stdio.be/criu/runhook.diff

The hook itself looks like this: http://stdio.be/criu/criu-ayhook.txt, at first there was no addition of the blackhole route, merely deleting all of the RA routes that were previously restored.

The initial testing looked promising, but when I attempted to move the container with an SSH session into it, I got:

`ubuntu@test4:~$ lxc move test4:aytest1 test5:aytest1`
`error: Error transferring container data: restore failed:`
`(00.366615)    158: Error (sk-inet.c:748): Can't connect inet socket back: Network is unreachable`
`(00.391988) Error (cr-restore.c:978): 15214 killed by signal 9: Killed`
`(00.396122) Error (cr-restore.c:1840): Restoring FAILED.`

Then I decided to modify the hook script in an attempt to workaround by adding the high-metric blackhole route, which resulted in a different error:

`error: Error transferring container data: restore failed:`
`(00.272288)    332: Error (sk-inet.c:748): Can't connect inet socket back: Invalid argument`
`(00.276921)    282: Error (cr-restore.c:975): 332 exited, status=1`
`(00.311247) Error (cr-restore.c:978): 15892 killed by signal 9: Killed`
`(00.312272) Error (cr-restore.c:1840): Restoring FAILED.`

Finally, I changed the blackhole into a bogus route, by making the command like this:

`ip -6 route add default via fe80::dead:beef dev eth0 metric 10000`

With this tweak to my hook script the SSH connection survives the migration, even though of course now there is a bogus additional default route in the container...

**Comment by xemul** [comment] 2016-07-09 17:27
OK. Well, methinks that the correct fix would be to make kernel accept timeouts from rtnl messages, so that dumped rtnl messages and restore of them is symmetrical.

**Comment by ayourtch** [comment] 2016-07-10 03:58
@xemul - if the kernel accepts timeouts, the NUD will still have to kick in, which might not be fast enough for some scenarios - so the hook might still be useful IMHO.. 

But yeah the dump/restore symmetricity should definitely be fixed anyway... what is the best way to proceed on that you think ?

**Comment by xemul** [comment] 2016-07-10 04:55
@ayourtch, it's to cook the kernel patch and submit one to the netdev@ ;) Presumably it will be ... challenging, I don't see where the RTA_CACHEINFO is considered at restore time at all :\
Would you like to try?

**Comment by ayourtch** [comment] 2016-08-07 11:17
Interestingly, there is a code to restore "expires" value, but it looks for a different RTA_* value... So since we are saving it into RTA_CACHEINFO, I've added the chunk to extract it from there.

But this has uncovered another problem - the flags are restored incorrectly. Hence, the other chunk in rtm_to_fib6_config.

What do you think about the below ?


`diff --git a/net/ipv6/route.c b/net/ipv6/route.c`
`index 4981755..f4a4caf 100644`
`--- a/net/ipv6/route.c`
`+++ b/net/ipv6/route.c`
`@@ -2769,6 +2769,15 @@ static int rtm_to_fib6_config(struct sk_buff *skb, struct nlmsghdr *nlh,`
` 	cfg->fc_protocol = rtm->rtm_protocol;`
` 	cfg->fc_type = rtm->rtm_type;`
` ` 
`+	if (rtm->rtm_protocol == RTPROT_RA) {`
`+	    cfg->fc_flags |= RTF_ADDRCONF;`
`+	    if (rtm->rtm_dst_len == 0) {`
`+		cfg->fc_flags |= RTF_DEFAULT;`
`+	    } else {`
`+		cfg->fc_flags |= RTF_ROUTEINFO;`
`+	    }`
`+	}`
`+`
` 	if (rtm->rtm_type == RTN_UNREACHABLE ||`
` 	    rtm->rtm_type == RTN_BLACKHOLE ||`
` 	    rtm->rtm_type == RTN_PROHIBIT ||`
`@@ -2844,6 +2853,12 @@ static int rtm_to_fib6_config(struct sk_buff *skb, struct nlmsghdr *nlh,`
` 	if (tb[RTA_ENCAP_TYPE])`
` 		cfg->fc_encap_type = nla_get_u16(tb[RTA_ENCAP_TYPE]);`
` ` 
`+	if (tb[RTA_CACHEINFO]) {`
`+		struct rta_cacheinfo *ci = nla_data(tb[RTA_CACHEINFO]);`
`+		cfg->fc_expires = ci->rta_expires;`
`+		cfg->fc_flags |= RTF_EXPIRES;`
`+	}`
`+`
` 	if (tb[RTA_EXPIRES]) {`
` 		unsigned long timeout = addrconf_timeout_fixup(nla_get_u32(tb[RTA_EXPIRES]), HZ);`

**Comment by xemul** [comment] 2016-08-10 09:10
Looks good. Would you try to push this into the netdev@ mailing list? :)

**Comment by ayourtch** [comment] 2016-08-10 14:09
Actually I just realized that blindly updating the expires from RTA_CACHEINFO will botch the static routes (and it does, somewhat - the expires goes into negatives, though the route still does not get deleted... and having the "if (fi->rta_expires)" conditional around setting the RTF_EXPIRES flag will create a nasty to track race if the route being dumped was just about to expire.... So I think I might need to add the code to generate the RTA_EXPIRES instead...

**Comment by ayourtch** [comment] 2016-08-11 13:12
All right, the candidate source for git-send-email to netdev is at: http://stdio.be/netdev/ra-route/

@tych0 , @xemul , @avagin - Could you give it a spin and tell me what you think ?

Also, if I grok the the logic of the kernel patch submission correctly, having "Signed-off-by" from someone besides me might help - so if anyone of you feels confident enough in these patches to test them and to qualify to have their name/email added as "Signed-off-by" when I send it, that might help too, please let me know!

**Comment by xemul** [comment] 2016-08-11 14:32
Well, the Signed-off-by: means that the patch was either prepared by the one(s) who signs or got into repo via one or more maintainers' branches.

Agreement with the change is expressed with Acked-by: or Reviewed-by:, if someone played with the patch for real, one may put Tested-by: .

**Comment by ayourtch** [comment] 2016-08-11 14:57
Sorry, thanks for the education! I misunderstood it to also mean a "strong ack".

**Comment by xemul** [comment] 2016-08-11 15:06
Well, there's a variety of -by: tags in the kernel :) Most popular are, of course, Signed-off, Acked and Reviewed, but ... people try to express themselves :)

$ git log --since '2 years ago' --no-merges | fgrep -- '-by:'  | awk '{print $1}' | sort | uniq -c | sort -n

**Comment by ayourtch** [comment] 2016-08-16 11:32
ok, I guess with no further comments I will ship the patches to netdev!

**Comment by xemul** [comment] 2016-10-20 11:29
So, @ayourtch , do you have any news about it?

**Comment by ayourtch** [comment] 2016-10-20 15:25
It didn't make the review, then I had a vacation and now got pulled into another project... Maybe I could give another shot submitting to netdev in a couple of weeks or so...

**Comment by xemul** [comment] 2019-06-27 12:32
I'm closing it for now. Once we have time and courage to get back to this, let's re-open.

**Closed by xemul** 2019-06-27 12:32 UTC
Labels: bug, dangling
