### ISSUE TITLE
dose you guys can run CRIU in ubuntu18

### ISSUE THREAD

**Issue by GitHubDiom** [checkpoint-restore/criu#641] opened 2019-03-05 08:05 UTC
recently i have clone CRIU's code for my test, but when a run the cmd , it happened ,and the test code(counting from 1 to 0x3f3f3f by sleep(1) per print ) is in /criu/test/ 
> criu -D `mycheckpoint` -j -t `pid`

but i get the wrong code:

Warn  (criu/image.c:135): Failed to open parent directory
Warn  (compel/arch/x86/src/lib/infect.c:273): Will restore 16872 with interrupted system call
Error (criu/files-reg.c:869): Can't dump ghost file /dev/shm/.org.chromium.Chromium.ma6Mdh of 4198400 size, increase limit
Error (criu/cr-dump.c:1345): Dump files (pid: 16872) failed with -1
Error (criu/cr-dump.c:1748): Dumping FAILED.

ps: im not good at describe someting in english .... sorry about that

**Comment by GitHubDiom** [comment] 2019-03-05 08:28
um ... yeah

**Comment by GitHubDiom** [comment] 2019-03-05 08:33
it happens when i run the code in VSCode,  but in terminal that looks good. so what makes CRIU cant kill the process when i using VScode as a compiler .
clearly, when i run the code in VsCode, then i dump the process doesn't make the process stop but running as normal. but when i run the code just in terminal(using gcc file and ./a.out command), it looks good that the process was dump and restore normally.

**Comment by rst0git** [comment] 2019-03-05 09:23
Hi @GitHubDiom 

I am not quite sure what went wrong in your case, but if you wish to build CRIU from within the Microsoft Visual Studio Code editor, please use the [integrated terminal](https://code.visualstudio.com/docs/editor/integrated-terminal) and enter `make`.

I hope this answers your question.

**Comment by GitHubDiom** [comment] 2019-03-05 10:21
Hi @rst0git 
thanks for your answer
yeah i am using this integrated terminal
i run the code(counting from 1 to 0x3f3f3f3f) through by type `./a.out` in terminal(VSCode one), and open another terminal(Ubuntu one), then i run the command `criu -D mycheckpoint_file -j -t pid` .
Normally the counting code should be terminated, but it still running and i check that the process continues(by `ps -ef | grep a.out`). But if i change to Ubuntu terminal(do not use VSCode's terminal but both on Ubuntu default terminal) and do it again, it all looks good,

**Comment by avagin** [comment] 2019-03-05 17:20
Could you show output for `cat /prod/pid/maps` and `ls -l /proc/pid/fd`?

**Comment by rst0git** [comment] 2019-03-05 20:17
I understand the issue now (@avagin thank you for the hint).

When we start an instance of an integrated terminal (in vscode), the shell (`bash`) inherits all file descriptors that were opened by the vscode process. Then, when we start a new process within that terminal/shell it will also inherits all those file descriptors.

As a result, if we call `criu dump` (in another terminal, outside vscode), it will fail.

> Normally the counting code should be terminated, but it still running and i check that the process continues

This is because `criu dump` fails to create a checkpoint and it recovers the running state of the specified process (this is expected behaviour).

@GitHubDiom Could you try the following as a workaround for that issue:

1. Open an integrated terminal in vscode
2. Run the following script inside that terminal:
```sh
FDS=$(find /proc/$BASHPID/fd -type l -printf '%f\n')
for n in $FDS ; do
        if ((n > 2)) ; then
                eval "exec $n>&-"
        fi
done
```
3. Start your process, for example `./a.out`
4. In another terminal, outside vscode, call `criu dump` (with appropriate options)
5. Then call `criu restore` (with appropriate options)

**Comment by GitHubDiom** [comment] 2019-03-20 11:51
hi @rst0git  @avagin   i am sorry to borther you 
I meet another question when i deploying CRIU....
## how can  i MAKE CRIU when i tpye `sudo make && sudo make install ` in share filesystem on windows.

- i have a shared file on windows
- i mount the share file on ubuntu
- connect ubuntu by ssh (from windows)
- then i want to modify CRIU's resource in my windows computer

### thats the code i type and the responses
> `sudo make DESTDIR=/home/diom/resources/`
> Note: Building without setproctitle() and strlcpy() support.
>       To enable these features, please install libbsd-devel (RPM) / libbsd-dev (DEB).
>   GEN      include/common/asm
> ln: failed to create symbolic link 'include/common/asm': Operation not supported
> Makefile:177: recipe for target 'include/common/asm' failed
> make: *** [include/common/asm] Error 1

> 
> `sudo make DESTDIR=/home/diom/resources/ install`
> Note: Building without setproctitle() and strlcpy() support.
>       To enable these features, please install libbsd-devel (RPM) / libbsd-dev (DEB).
>   INSTALL  criu.8
>   INSTALL  crit.1
>   GEN      include/common/asm
> ln: failed to create symbolic link 'include/common/asm': Operation not supported
> Makefile:177: recipe for target 'include/common/asm' failed
> make: *** [include/common/asm] Error 1
> 



· it looks cannot build `link` when across different file system(linux and windows)

- someone told me to type ` ./configuer --prefix=/install_path ` and then CRIU will installed in `/install_path/bin` 
- but i found that there have no `configure` , so how can i do this (cause i want to work on my windows computer ... )

**Comment by rst0git** [comment] 2019-03-20 18:23
@GitHubDiom
```
$ make && sudo make install PREFIX=/usr
```

**Comment by GitHubDiom** [comment] 2019-03-21 02:24
> @GitHubDiom
> 
> ```
> $ make && sudo make install PREFIX=/usr
> ```

that is the issue ..

> Note: Building without setproctitle() and strlcpy() support.
      To enable these features, please install libbsd-devel (RPM) / libbsd-dev (DEB).
  GEN      include/common/asm
ln: failed to create symbolic link 'include/common/asm': Operation not supported
Makefile:177: recipe for target 'include/common/asm' failed
make: *** [include/common/asm] Error 1

feeling sad...

**Comment by adrianreber** [comment] 2019-03-21 14:05
It sounds like your file-system does not support creating symbolic links. The CRIU build process needs it, so you have to use another file-system to build CRIU. Maybe a ramdisk?

**Comment by GitHubDiom** [comment] 2019-03-21 14:12
@adrianreber  thank you 
this happened when i put all CRIU file in shared file (on windows and mount it on linux by cifs), but once i `make && make install ` CRIU on Ubuntu file system(means NOT in shared file), all is fine. 

Is it because of the difference in the file system? （windows and linux）

**Comment by adrianreber** [comment] 2019-03-21 14:17
Not really sure, but it seems the windows file system does not support symbolic links.

**Comment by adrianreber** [comment] 2019-04-25 19:55
Closing this. This seems to be solved. Please re-open if necessary.

**Closed by adrianreber** 2019-04-25 19:55 UTC
Labels: question
