### ISSUE TITLE
error: snapshot dump failed

### ISSUE THREAD

**Issue by adityacloud1** [checkpoint-restore/criu#508] opened 2018-06-13 05:20 UTC
To start live migration using LXD in docker my experimental setup is as follows:

Physical machine OS: Ubuntu 16.04
Docker version 17.06.0-ce, build 02c1d87
lxc --version 2.0.11
lxd --version 2.0.11
criu --version Version: 2.6

After successful installation of container named 'c1' i run the following command to save the current states of the container to disk:

sudo lxc snapshot c1 checkpoint-2 --stateful

But it gives following errors:
error: snapshot dump failed
(00.260241) Error (criu/sk-netlink.c:73): The socket has data to read
(00.260268) Error (criu/cr-dump.c:1313): Dump files (pid: 9158) failed with -1
(00.303791) Error (criu/cr-dump.c:1628): Dumping FAILED.

Any, help will be appreciated. Solutions can be emailed directly at: adityaform@gmail.com
![criu snapshot dump error](https://user-images.githubusercontent.com/40225508/41331621-8984d6d4-6ef7-11e8-8f53-59ab6343eaf6.png)

**Comment by rst0git** [comment] 2018-06-13 08:53
Hi @adityacloud1 

Would it be possible to upgrade CRIU to version 3.9?

**Comment by adityacloud1** [comment] 2018-06-16 05:35
I upgrade to 3.9 and run the following commands:
 sudo lxc snapshot c1 checkpoint-2 --stateful 
![snapshot dump failed](https://user-images.githubusercontent.com/40225508/41496116-2919feea-7155-11e8-9537-85569a51d1f3.png)

Now Error is as follows
error: snapshot dump failed
(01.134200) Error (criu/parasite-syscall.c:532): Unable to connect a transport socket: Permission denied
(01.134218) Error (criu/parasite-syscall.c:134): Can't block signals for 7097: No such process
(01.134237) Error (criu/cr-dump.c:1244): Can't infect (pid: 7097) with parasite
(01.158480) Error (criu/ptrace.c:54): Unable to detach from 7097: No such process
(01.158696) Error (criu/cr-dump.c:1628): Dumping FAILED.

**Comment by adrianreber** [comment] 2018-06-17 12:37
Can you, for testing, disable Apparmor. I think we have seen a similar error which was related to Apparmor.

**Comment by adrianreber** [comment] 2018-06-27 17:42
I am closing this as it seems to be a duplicate of #439

**Closed by adrianreber** 2018-06-27 17:42 UTC

**Comment by adityacloud1** [comment] 2018-06-28 04:13
Thanks everyone for yours comments.
