### ISSUE TITLE
(zdtm/thp_disable) get_smaps_bits.c: VmFlags not found

### ISSUE THREAD

**Issue by rst0git** [checkpoint-restore/criu#1346] opened 2021-01-25 22:07 UTC
The `zdtm/thp_disable` test fails with the following error:
```
======================= Run zdtm/static/thp_disable in h =======================
Start test
./thp_disable --pidfile=thp_disable.pid --outfile=thp_disable.out
make: *** [Makefile:426: thp_disable.pid] Error 1
 Test zdtm/static/thp_disable FAIL at ['make', '--no-print-directory', '-C', 'zdtm/static', 'thp_disable.pid'] 
Test output: ================================
09:47:26.130:    52: Fetch existing flags/adv
09:47:26.130:    52: ERR: get_smaps_bits.c:122: VmFlags not found for 7f08ef89d000 (errno = 2 (No such file or directory))
09:47:26.130:    51: ERR: test.c:316: Test exited unexpectedly with code 255
```
By adding a debug print statement, I noticed that the mmap address gets rounded to 4K.
```diff
--- a/test/zdtm/static/get_smaps_bits.c
+++ b/test/zdtm/static/get_smaps_bits.c
@@ -109,6 +109,7 @@ int get_smaps_bits(unsigned long where, unsigned long *flags, unsigned long *mad
        while (fgets(buf, sizeof(buf), smaps)) {
                is_vma_range_fmt(buf, &start, &end);
 
+               printf("%lu %lu | %s", start, where, buf);
                if (!strncmp(buf, "VmFlags: ", 9) && start == where) {
                        found = 1;
                        parse_vmflags(buf, flags, madv);

```
```
(start)        (where)
-------------------------------------------------------------------------
139894293479424 139894293483520 | 7f3badab4000-7f3badcb5000 rw-p 00000000 00:00 0 
139894293479424 139894293483520 | Size:               2052 kB
139894293479424 139894293483520 | KernelPageSize:        4 kB
139894293479424 139894293483520 | MMUPageSize:           4 kB
139894293479424 139894293483520 | Rss:                   4 kB
139894293479424 139894293483520 | Pss:                   4 kB
139894293479424 139894293483520 | Shared_Clean:          0 kB
139894293479424 139894293483520 | Shared_Dirty:          0 kB
139894293479424 139894293483520 | Private_Clean:         0 kB
139894293479424 139894293483520 | Private_Dirty:         4 kB
139894293479424 139894293483520 | Referenced:            4 kB
139894293479424 139894293483520 | Anonymous:             4 kB
139894293479424 139894293483520 | LazyFree:              0 kB
139894293479424 139894293483520 | AnonHugePages:         0 kB
139894293479424 139894293483520 | ShmemPmdMapped:        0 kB
139894293479424 139894293483520 | FilePmdMapped:        0 kB
139894293479424 139894293483520 | Shared_Hugetlb:        0 kB
139894293479424 139894293483520 | Private_Hugetlb:       0 kB
139894293479424 139894293483520 | Swap:                  0 kB
139894293479424 139894293483520 | SwapPss:               0 kB
139894293479424 139894293483520 | Locked:                0 kB
139894293479424 139894293483520 | THPeligible:		0
139894293479424 139894293483520 | VmFlags: rd wr mr mw me ac sd 
139894293479424 139894293483520 | 7f3badab4000-7f3badcb5000 rw-p 00000000 00:00 0 
```
It looks like this problem has been addressed with a workaround in commit https://github.com/checkpoint-restore/criu/commit/f487c965d441809da1f28b0337ec350d7bfb119e.

**Comment by rst0git** [comment] 2021-01-25 22:07
@rppt Do you have any ideas how to fix this error?

**Comment by avagin** [comment] 2021-01-26 03:30
Where does this test fail?

BTW: I think you need to use %lx to print addresses:
printf("%lx %lx | %s", start, where, buf);

**Comment by rst0git** [comment] 2021-01-26 07:04
https://github.com/checkpoint-restore/criu/pull/1347/checks?check_run_id=1766734652
https://github.com/checkpoint-restore/criu/pull/1344/checks?check_run_id=1760944936
https://github.com/checkpoint-restore/criu/pull/1343/checks?check_run_id=1756881359

**Comment by rppt** [comment] 2021-01-26 08:59
> @rppt Do you have any ideas how to fix this error?

TBH, no :)
I'll try to take a look at this next week

**Comment by avagin** [comment] 2021-01-27 08:58
I think the problem is that a test vma is merged with another vma. The kernel can do this if both vma-s have been mapped with the same flags.

**Closed** 2021-01-29 17:08 UTC
