### ISSUE TITLE
Massive testsuite failures when testing from a subdirectory of /tmp on Fedora (starting with zdtm/static/aio00)

### ISSUE THREAD

**Issue by fweimer-rh** [checkpoint-restore/criu#2441] opened 2024-07-10 17:07 UTC
Fedora 39 mounts `/tmp` like this:

```
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,seclabel,nr_inodes=1048576,inode64)
```

This seems to cause all tests to fail if the CRIU Git checkout is located in `/tmp`. It's a bit non-obvious, so maybe the testsuite could check the mount flags of the mount point? At the very least, this ticket should be easier to find due to the `zdtm/static/aio00` string …

**Comment by avagin** [comment] 2024-07-10 22:13
Our tests creates a test root file system to run tests in a container-like environment:
https://github.com/checkpoint-restore/criu/blob/criu-dev/test/zdtm.py#L251

We probably can do something like this:
https://github.com/avagin/criu/commit/0e477f336fcc6b857cfb24334986dec28ebad7c1

@adrianreber could you try to run these tests with my patch?

**Comment by avagin** [comment] 2024-07-11 07:54
@adrianreber I just found that my change is incomplete. I will update it and push the new version tomorrow.

**Comment by avagin** [comment] 2024-07-12 07:31
My origin idea doesn't work. I think the simplest way to fix the issue is to do something like this:
```diff --git a/tests/run-zdtm.sh b/tests/run-zdtm.sh
index 56fc8ec..45b1d3e 100755
--- a/tests/run-zdtm.sh
+++ b/tests/run-zdtm.sh
@@ -24,7 +24,7 @@ EXCLUDES=" \
        -x zdtm/static/cgroup02 "
 
 run_test() {
-       ./zdtm.py run --criu-bin /usr/sbin/criu ${EXCLUDES} \
+       ./test/zdtm.py run --criu-bin /usr/sbin/criu ${EXCLUDES} \
                -a --ignore-taint --keep-going
 
        RESULT=$?
@@ -42,11 +42,14 @@ rm -f /var/lib/sss/pipes/nss
 
 cd source
 
+tar -czf test.tar.gz -C test .
+mount -t tmpfs criu-test test
+trap "umount -l test" EXIT
+tar -xzf test.tar.gz -C test
+
 echo "Build CRIU"
 make
 
-cd test
-
 echo "Run the actual CRIU test suite"
 run_test
```

**Comment by rst0git** [comment] 2024-07-12 09:26
> maybe the testsuite could check the mount flags of the mount point?

It sounds like a good idea.

> I think the simplest way to fix the issue is to do something like this

@avagin Would it make sense for ZDTM to exit with an error message describing the problem?

**Comment by Snorch** [comment] 2024-07-15 02:44
> This seems to cause all tests to fail if the CRIU Git checkout is located in /tmp.

Without any logs of failure there is no way to confirm that what you are describing is the same to what others may experience. Can you please follow the Issue creation template, and `**CRIU logs and information:**` specifically when reporting issues?

**Comment by Snorch** [comment] 2024-07-15 06:54
I agree with @rst0git, it seems like to much an effort to use external mount to provide device files into zdtm container.

Let's just print clear message that 'nodev' is a no-go option for criu repo if you want to run zdtm: https://github.com/checkpoint-restore/criu/pull/2444

**Comment by Snorch** [comment] 2024-07-16 02:51
We've talked with @avagin yesterday, and came to the conclusion that we probably should go with Andrei's "external mount" approach (https://github.com/avagin/criu/commit/38bab464b0c948ff22696f3d5b106dae656ea196), as the tendency is to add `nodev` to every filesystem except devtmpfs, and sooner or later we will face the problem that all available filesystems have it. So I'm closing my "just print clear message" PR in favor of Andrei's patch.

**Closed** 2024-07-22 14:44 UTC
