### ISSUE TITLE
Segmentation Error 

### ISSUE THREAD

**Issue by emanuelebevegni** [checkpoint-restore/criu#541] opened 2018-08-21 08:57 UTC
Hi everyone!
Im making a university project with criu but im kinda new to the linux and criu world. After installing criu, following ur video here on github, i try the simple loop example but it doesnt work out. When i try to use the command criu dump -t 2221 -vvv -o dump.log && echo OK or criu dump -D PP -t 4008 -v4 -o pp.log the target procces stoped but i recevied a "Segmentation error (core dump created)", i check everything i can but still not working. If i use the second dump command in the log i have this errors "00.023857) Error (criu/parasite-syscall.c:92): si_code=4 si_pid=4008 si_status=11
(00.023862) Error (criu/parasite-syscall.c:100): 4008 was stopped by 11 unexpectedly"
Infact if i try the restore command nothing happend. If u have any idea to help me it would be great.
Im using Fedora release 28 (Twenty Eight) and kerner 4.16.13-300.fc28.x86_64.
Thanks to everyone!

**Comment by emanuelebevegni** [comment] 2018-08-21 10:01
the command are in the message i post same things for the log file.

**Comment by 0x7f454c46** [comment] 2018-08-21 13:03
There is a bit of misunderstanding: Adrian asks you about *full* log - lines in the log that precede error usually being helpful.

**Comment by emanuelebevegni** [comment] 2018-08-21 13:27
I already post everything pop out on the command line after i use the command dump.

**Comment by rst0git** [comment] 2018-08-21 15:29
Hi @emanuelebevegni 
Would you be able to upload the `dump.log` and `pp.log` files generated from the above commands?

**Comment by emanuelebevegni** [comment] 2018-08-21 15:37
Sure when i go back to the university lab

**Comment by emanuelebevegni** [comment] 2018-08-23 13:38
dump.log was made by using the first command i put in my first comment, pp2 was made by using the second command (i forgot to write the 2 in the comment before PP)
[pp2.log](https://github.com/checkpoint-restore/criu/files/2314616/pp2.log)
[dump.log](https://github.com/checkpoint-restore/criu/files/2314617/dump.log)

**Comment by rst0git** [comment] 2018-08-23 14:40
Hi @emanuelebevegni 
Can you describe what steps you followed to create, run and checkpoint the simple loop example? (I am trying to reproduce the issue)

**Comment by emanuelebevegni** [comment] 2018-08-23 14:50
the same step are in the installation video plus installing all the package and the same things for the simple loop example. Nothing more than that. The installation was a success and i have the same output of the video, i read every line and even the zdtm test was a success without problem.

**Comment by rst0git** [comment] 2018-08-23 15:08
Ok, what happens when you run the following? 
```
cat > test.sh <<-EOF
#!/bin/sh
while :; do
    sleep 1
    date
done
EOF
chmod +x test.sh
setsid ./test.sh  < /dev/null &> test.log &
sudo criu dump -t $(pgrep -f test.sh) -v4 -o dump.log
```

**Comment by emanuelebevegni** [comment] 2018-08-23 15:12
Same result :(

**Comment by rst0git** [comment] 2018-08-23 18:41
Hi @emanuelebevegni, would you be able to share the `dump.log` from the last attempt?

I noticed a some differences between the `pp2.log` / `dump.log` files and the log file that CRIU generates for me. (I used Fedora 28 with 4.16.13-300.fc28.x86_64 and CRIU v3.8.1)

```
[pp2.log]

(00.019520) Collecting mappings (pid: 4008)
(00.019526) ----------------------------------------
(00.019810) Dumping path for -3 fd via self 7 [/root/criu/test/prova]
...
(00.020488) Collected, longest area occupies 512 pages
...
(00.021997) Dumping opened files (pid: 4008)
(00.022003) ----------------------------------------
(00.022014) Sent msg to daemon 71 0 0
pie: 4008: __fetched msg: 71 0 0
pie: 4008: __sent ack msg: 71 71 0
pie: 4008: Daemon waits for command
(00.022038) Wait for ack 71 on daemon socket
(00.022046) Fetched ack: 71 71 0
(00.022084) 4008 fdinfo 0: pos:                0 flags:           100002/0
(00.022108) tty: Dumping tty 7 with id 0x4
(00.022116) Dumping path for 0 fd via self 7 [/dev/pts/1]
(00.022129) Sent msg to daemon 73 0 0
(00.022133) Wait for ack 73 on daemon socket
pie: 4008: __fetched msg: 73 0 0
pie: 4008: __sent ack msg: 73 73 0
(00.022178) Fetched ack: 73 73 0
pie: 4008: Daemon waits for command
(00.022298) 4008 fdinfo 1: pos:                0 flags:           100002/0
(00.022337) 4008 fdinfo 2: pos:                0 flags:           100002/0
(00.022362) ----------------------------------------
...
(00.022454) Dumping pages (type: 52 pid: 4008)
(00.022457) ----------------------------------------
(00.022461)    Private vmas 512/1078 pages
(00.022477) pagemap-cache: created for pid 4008 (takes 4096 bytes)
```



```
[Reproduce]

(00.009784) Collecting mappings (pid: 3180)
(00.009787) ----------------------------------------
(00.009984) Dumping path for -3 fd via self 7 [/usr/bin/bash]
...
(00.010703) Collected, longest area occupies 51154 pages
...
(00.011207) Dumping opened files (pid: 3180)
(00.011214) ----------------------------------------
(00.011221) Sent msg to daemon 71 0 0
pie: 3180: __fetched msg: 71 0 0
pie: 3180: __sent ack msg: 71 71 0
pie: 3180: Daemon waits for command
(00.011255) Wait for ack 71 on daemon socket
(00.011260) Fetched ack: 71 71 0
(00.011280) 3180 fdinfo 0: pos:                0 flags:           100000/0
(00.011295) Dumping path for 0 fd via self 7 [/dev/null]
(00.011326) 3180 fdinfo 1: pos:             0x1d flags:           100001/0
(00.011336) Dumping path for 1 fd via self 9 [/home/rst/test/test.log]
(00.011351) 3180 fdinfo 2: pos:             0x1d flags:           100001/0
(00.011369) 3180 fdinfo 255: pos:             0x30 flags:          2100000/0x1
(00.011376) Dumping path for 255 fd via self 11 [/home/rst/test/test.sh]
(00.011381) ----------------------------------------
(00.011401) Sent msg to daemon 65 0 0
(00.011406) Wait for ack 65 on daemon socket
pie: 3180: __fetched msg: 65 0 0
pie: 3180: __sent ack msg: 65 65 0
pie: 3180: Daemon waits for command
(00.011541) Fetched ack: 65 65 0
(00.011548) 
(00.011551) Dumping pages (type: 52 pid: 3180)
(00.011554) ----------------------------------------
(00.011557)    Private vmas 51154/53591 pages
(00.011578) pagemap-cache: created for pid 3180 (takes 409232 bytes)
```

**Comment by emanuelebevegni** [comment] 2018-08-23 19:18
Ok i will share it when i can. Maybe the difference is because i use different command, in pp2.log i specify the destination folder where criu have to generate the images.

**Comment by 0x7f454c46** [comment] 2018-08-23 19:19
```
(00.017942) Dumping core (pid: 3740)
(00.017945) ----------------------------------------
(00.017947) Obtaining personality ... 
(00.017968) Sent msg to daemon 64 0 0
(00.017972) Wait for ack 64 on daemon socket
pie: 3740: __fetched msg: 64 0 0
(00.018038) Error (criu/parasite-syscall.c:92): si_code=4 si_pid=3740 si_status=11
(00.018042) Error (criu/parasite-syscall.c:100): 3740 was stopped by 11 unexpectedly
```
+Cc: @cyrillos 
Well, that means parasite has segfaulted during infection.
Usually, that means that there is something borked during a build.
Could you share:
1. Output of `make V=1` during the build.
2. Those two binaries: criu/pie/parasite.o criu/pie/parasite.built-in.o

I suspect that you've got some excessive cflag from Fedora's environment. (Like build salt or something they do these days). And it breaks the parasite.

**Comment by emanuelebevegni** [comment] 2018-08-23 19:30
@adrianreber i cant install that package the system say is arleady updated.

**Comment by adrianreber** [comment] 2018-08-23 19:34
@emanuelebevegni According to https://bodhi.fedoraproject.org/updates/FEDORA-2018-2682c9b962 3.10-4.fc28 is the latest version for Fedora 28.

**Comment by 0x7f454c46** [comment] 2018-08-23 19:54
Thanks, @adrianreber.
I see your report here: https://lists.openvz.org/pipermail/criu/2018-July/041991.html
I planned to have a fix for that in TODO, but probably managed to forget.
Will take a look and fix it this week.

**Comment by adrianreber** [comment] 2018-08-23 19:57
@0x7f454c46 I think it is only a problem if building an RPM. That's why I updated the Fedora RPMs to no use annobin. It shouldn't be a problem if building from source on Fedora

**Comment by rst0git** [comment] 2018-08-24 08:41
Adrian thank you for pointing out the issue!

@emanuelebevegni I think you need to enable the `updates` repository. 
```
sudo dnf config-manager --set-enabled updates
```

**Comment by emanuelebevegni** [comment] 2018-08-24 09:45
I wll try all these things on these monday, because the university lab today is close for maintenance and on the week end all the university is close. Thx all for the help and see u soon.

**Comment by rst0git** [comment] 2018-08-27 17:33
Hi @emanuelebevegni

Good to hear that it works now! Can we close the issue?

It is not simple to checkpoint and restore Firefox because it is a GUI application. You can find more information about this in https://criu.org/VNC

If you just want to migrate a program from one PC to another, you can try to follow the example for lazy migration in https://criu.org/Lazy_migration

**Comment by emanuelebevegni** [comment] 2018-08-28 10:49
@rst0git yes u can close it i will try to checkpoint and restore firefox as example because for my project i need to stop a gui application. Thx a lot to all

**Closed** 2018-11-30 22:55 UTC
