### ISSUE TITLE
Live migration of an application result in lower performance

### ISSUE THREAD

**Issue by planetA** [checkpoint-restore/criu#1171] opened 2020-08-06 23:10 UTC
Hello,

I have quite a weird performance issue. 

I have an MPI multiprocess application running on two nodes. The application consists of 4 processes (ranks). Each node starts with 2 processes. Soon, I live-migrate one of the processes to another node. This results in significant performance degradation that cannot be explained by the migration time. For example, if a normal run takes around 35 seconds, with migration, the program runs for around 65 seconds. The migration time is less than 2 seconds.

If I start the application with 3 processes on one node from the very beginning, the runtime is still around 35 seconds (I have 4 cores per node). This indicates that the problem is not about resource exhaustion.

I found that the problem is somehow connected to the usage of vector instructions. To confirm my hypotheses I was running `perf stat` repeatedly for 200 ms while the application was running. Here is a typical sample after one of the processes migrates:

```
Performance counter stats for process id '154166':

       775,326,343      cycles                                                        (32.58%)
       611,253,031      instructions              #    0.79  insn per cycle           (42.54%)
        61,378,465      branch-instructions                                           (44.53%)
               156      avx_insts.all                                                 (46.51%)
                 0      other_assists.avx_to_sse                                      (33.57%)
                 0      other_assists.sse_to_avx                                      (31.92%)

       0.200672137 seconds time elapsed


 Performance counter stats for process id '154165':

       775,240,259      cycles                                                        (32.99%)
       616,100,734      instructions              #    0.79  insn per cycle           (42.95%)
        61,929,959      branch-instructions                                           (44.95%)
               127      avx_insts.all                                                 (46.93%)
                 0      other_assists.avx_to_sse                                      (33.15%)
                 0      other_assists.sse_to_avx                                      (31.91%)

       0.200609032 seconds time elapsed


 Performance counter stats for process id '154234':

       774,536,014      cycles                                                        (33.41%)
       324,489,301      instructions              #    0.42  insn per cycle           (43.38%)
        32,593,842      branch-instructions                                           (45.37%)
         4,951,097      avx_insts.all                                                 (47.36%)
         2,481,913      other_assists.avx_to_sse                                      (32.71%)
         2,487,357      other_assists.sse_to_avx                                      (31.90%)

       0.200649176 seconds time elapsed
```

The last process is the migrated one. You can notice that this process has significantly lower instruction per cycle count. This seems to be caused by AVX instructions, which are not used by other processes. I want to point out that all the processes doing essentially the same thing and should not differ significantly on any measure.

For further investigation, I measured the migrated and non-migrated process using `perf record` over 10 seconds in the middle of the run. I expect to see no significant difference, nevertheless, I see the following:

```
~# perf diff perf-fast.data perf-migr.data
# Event 'cycles'
#
# Baseline  Delta Abs  Shared Object     Symbol                                        
# ........  .........  ................  ..............................................
#
    28.43%     +8.39%  libm-2.31.so      [.] __ieee754_log_fma
     5.81%     -2.70%  ep.C.x            [.] vranlc_
    58.30%     -2.09%  ep.C.x            [.] MAIN__
     2.76%     -1.69%  ep.C.x            [.] log@plt
     2.40%     -0.85%  libm-2.31.so      [.] @plt
     1.73%     -0.73%  libm-2.31.so      [.] log@@GLIBC_2.29
```

From this data, you can see that the migrated process (`perf-migr.data`) spends significantly more time in `__ieee754_log_fma`.

Could you please help me with an explanation of what could have happened here and why migration may change the application behaviour?

**Comment by adrianreber** [comment] 2020-08-07 07:50
I highly doubt that I can answer your question, but I have a couple of questions about your setup.

> I have an MPI multiprocess application running on two nodes.

Which MPI implementation do you use?

> The application consists of 4 processes (ranks). Each node starts with 2 processes.

So on both nodes you have the controlling MPI process and two ranks? How do the ranks communicate with each other?
Looking at Open MPI I always see the controlling process (orted) which spawns the ranks, which are doing the actual calculations.

> Soon, I live-migrate one of the processes to another node.

A third node with a new controlling process which controls the migrated rank? So one node with two ranks and two nodes each with one rank? This is the first time I heard about an integration of CRIU in an MPI implementation. I worked on it about 8 years ago, but as far as I know all my code changes have been removed from Open MPI.

Are all CPUs the same on all nodes? I would expect that a 'normal' process does a CPU detection and, if it can do runtime optimization selection, selects which instructions are best for the current CPU. Or the shared object loader selects a certain optimized library for your current CPU. If you migrate the process to another CPU, the process might still use the optimization targeted for the initial CPU, if it is not aware of migration.

To understand the problem better, it should be possible to create a test case without MPI. Just the same calculation running in a single process and after migration the problem should be the same, right?

**Comment by planetA** [comment] 2020-08-07 08:59
> I highly doubt that I can answer your question, but I have a couple of questions about your setup.

I'm grateful for any help :) 

> Which MPI implementation do you use?

I use OpenMPI 4.0.2 running on top of UCX 1.6.1, but I suspect this is actually irrelevant. The benchmark I'm using is EP (embarrassingly parallel). This benchmark has less than 5 MPI collectives at the beginning and less than 5 in the end (together with MPI_Finalise). I migrate, when there is no communication whatsoever.

> So on both nodes you have the controlling MPI process and two ranks? How do the ranks communicate with each other?
> Looking at Open MPI I always see the controlling process (orted) which spawns the ranks, which are doing the actual
> calculations.

Each rank runs in a container of my own runc's libcontainer-based runtime. They communicate over vxlan-based overlay network. First I create containers running sshd servers, so that MPI can connect to them over normal ssh. The container migrates with all its processes, including sshd.

> A third node with a new controlling process which controls the migrated rank? So one node with two ranks and two nodes each with one rank? 

There is no third node. I migrate from node 1 to node 2. From (2 processes, 2 processes) to (1, 3).

> I worked on it about 8 years ago, but as far as I know all my code changes have been removed from Open MPI.

I don't rely on any changes inside OpenMPI or anything inside the container for that matter.

> Are all CPUs the same on all nodes? 

Nodes are identical.

> I would expect that a 'normal' process does a CPU detection and, if it can do runtime optimization selection, selects which instructions are best for the current CPU. 

From all I can see, in particular, the assembly shown by `perf report`, they run absolutely the same code, the same instructions. I can do additional checks (which?) and share any logs to confirm or refute this statement.

> If you migrate the process to another CPU, the process might still use the optimization targeted for the initial CPU, if it is not aware of migration.

There is no difference if I migrate from node 1 to node 2, or node 2 to node 1: The performance drop is the same.

> To understand the problem better, it should be possible to create a test case without MPI. Just the same calculation running in a single process and after migration the problem should be the same, right?

I guess so. From all I can see right now, it doesn't have to do with MPI actually.

I will try to come up with MWE.

**Comment by adrianreber** [comment] 2020-08-07 10:24
Interesting project.

How many non-hyperthreading cores are on each node?

Is only the migrated process on the destination node slower? The original processes keep on running with the same performance?

What happens if you migrate the bad performing process back to each original node?

Is Open MPI doing any pinning of the processes to a certain core to avoid that the process is scheduled on different cores? Does the restored process maybe change cores? Are three process on one system bad for the CPU caches? Is it a memory bandwidth problem?

I think the most interesting part is that:
```
         4,951,097      avx_insts.all                                                 (47.36%)
         2,481,913      other_assists.avx_to_sse                                      (32.71%)
         2,487,357      other_assists.sse_to_avx                                      (31.90%)
```

The migrated process is doing a lot of transitions from AVX to legacy SSE (other_assists.avx_to_sse) and back to AVX (other_assists.sse_to_avx). According to some documentation I found this includes a penalty. Maybe there is indeed a bug in CRIU which does not migrate some AVX state correctly which leads to these transitions which make everything slow.

If you can find a simple reproducer and run it once with AVX and once without AVX this would make this clearer.

@checkpoint-restore/maintainers anyone any other ideas?

**Comment by planetA** [comment] 2020-08-07 10:51
> How many non-hyperthreading cores are on each node?

4 cores each with two hyperthreads. I tried to disable HT by shutting down HT over sysfs, with the same result.

> Is only the migrated process on the destination node slower? 

Yes.

> The original processes keep on running with the same performance?

Yes. And if I don't migrate at all, all processes have normal performance.

> Is Open MPI doing any pinning of the processes to a certain core to avoid that the process is scheduled on different cores? 

No, but CFS takes care of that quite nice. I manually tried to pin the cores, nothing really changed.

> Are three process on one system bad for the CPU caches?

I don't think so. If I start 3 processes on single node from the beginning, I get normal performance.

> I think the most interesting part is that:

Indeed. Given that the program doesn't actually use AVX instructions (other processes don't use them almost at all), it seems to me that the core somehow suddenly starts running SSE instructions with AVX engine and for that requires a lot of transitions from SSE to AVX and back. Notice that ration of AVX instructions is almost 1:1 to avx_to_sse + sse_to_avx (less than 0.5% difference).

>  According to some documentation I found this includes a penalty.

That seems to be the source of the performance difference, although it is unclear why this happens in the first place.

> If you can find a simple reproducer

Working on it.

**Comment by planetA** [comment] 2020-08-07 11:32
I guess, I found a temporary fix. I add `noxsave` to linux boot command line. Now the situation after migration looks as follows:

```
 Performance counter stats for process id '28841':

       777,288,890      cycles                                                        (64.92%)
       678,887,860      instructions              #    0.87  insn per cycle           (82.85%)
        59,993,781      branch-instructions                                           (84.06%)
               116      avx_insts.all                                                 (84.03%)
                 0      other_assists.avx_to_sse                                      (84.06%)
                 0      other_assists.sse_to_avx                                      (82.95%)

       0.200557394 seconds time elapsed


 Performance counter stats for process id '28918':

       778,005,375      cycles                                                        (65.69%)
       679,504,521      instructions              #    0.87  insn per cycle           (83.64%)
        59,994,476      branch-instructions                                           (84.05%)
               111      avx_insts.all                                                 (84.04%)
                 0      other_assists.avx_to_sse                                      (84.04%)
                 0      other_assists.sse_to_avx                                      (82.19%)

       0.200583193 seconds time elapsed


 Performance counter stats for process id '28842':

       776,789,264      cycles                                                        (64.46%)
       678,968,826      instructions              #    0.87  insn per cycle           (82.41%)
        60,021,245      branch-instructions                                           (84.03%)
               114      avx_insts.all                                                 (84.06%)
                 0      other_assists.avx_to_sse                                      (84.03%)
                 0      other_assists.sse_to_avx                                      (83.44%)

       0.200558838 seconds time elapsed
```

Process `28918` is the one that has migrated, but as you can see it is basically indistinguishable from the rest. And the overall performance is within some reasonable limits now.

I'm afraid I will have to postpone this issue (unless it hits me again) for couple of weeks because I'm working hard for a specific deadline now. But I will definitely continue the investigation in the end of August. Please, do not close the issue until then :)

**Comment by adrianreber** [comment] 2020-08-07 13:02
Good that you found a workaround and this points even more at this being a bug which should be fixable.

**Comment by cyrillos** [comment] 2020-08-07 17:34
To be honest avx/avx2/avx512 never been tested deep enough, so there could be some bugs in criu. `noxsave` added to the command line of a kernel forces it to not use `xsave` frame (and in result some of instructions won't be available). This requires pretty deep investigation. Maybe @0x7f454c46 find some spare time to look into.

**Comment by planetA** [comment] 2020-08-31 19:16
I found a simpler reproducer. The (NAS parallel benchmarks)[https://www.nas.nasa.gov/assets/npb/NPB3.4.1.tar.gz] have an OpenMP-based version. If I use just it, I observe the same bug. See the following [asciicinema](https://asciinema.org/a/osDNAis7QkvOojbmrsDVhAqH0).

I compiled ep benchmark inside NPB3.4/NPB3.4-OMP directory using `make ep CLASS=C` command. I just had to copy the template config before compilation: `cp config/make.def.template config/make.def`

**Comment by planetA** [comment] 2020-09-07 09:26
@cyrillos @adrianreber Sorry to bug you. But is this example helpful?

**Comment by cyrillos** [comment] 2020-09-07 09:30
@planetA Sorry, I've had no time to investigate, and I fear I won't in near future :-( Maybe Dima will manage to? @0x7f454c46

**Comment by 0x7f454c46** [comment] 2020-09-07 16:14
I'll try to find time to look at it this week, it's on my todo.

**Comment by 0x7f454c46** [comment] 2021-03-08 14:30
I've looked at this last week. It's reproducible with the mentioned benchmark:
```
    20.12%     +8.16%  libm-2.33.so            [.] __ieee754_log_fma
    66.00%     -7.41%  ep.C.x                  [.] MAIN__._omp_fn.1
     0.90%     -0.32%  libm-2.33.so            [.] 0x000000000000f2e0
     0.89%     -0.32%  ep.C.x                  [.] log@plt
     0.90%     -0.29%  libm-2.33.so            [.] log@@GLIBC_2.29
               +0.26%  [kernel.kallsyms]       [k] 0xffffffff844058d0
    11.11%     -0.06%  ep.C.x                  [.] vranlc_
```
Though, I have Kaby Lake CPU and it doesn't have those counters (from the report):
```
          4,951,097      avx_insts.all                                                 (47.36%)
         2,481,913      other_assists.avx_to_sse                                      (32.71%)
         2,487,357      other_assists.sse_to_avx                                      (31.90%)
```

Looking at `__ieee754_log_fma()` disasm it has some amount of FMA instructions, i.e:
```
  ab:   c4 e2 c1 99 41 10       vfmadd132sd 0x10(%rcx),%xmm7,%xInmm0
  b1:   c4 e2 f1 a9 51 18       vfmadd213sd 0x18(%rcx),%xmm1,%xmm2
  b7:   c4 e2 f9 a9 2d 00 00    vfmadd213sd 0x0(%rip),%xmm0,%xmm5
```
While `MAIN__._omp_fn.1` disasm has SSE2 instructions, i.e:
```
 18.36 │       sqrtsd    %xmm0,%xmm0
  3.62 │       mulsd     %xmm0,%xmm2
  0.40 │       mulsd     %xmm0,%xmm1
  1.13 │       movapd    %xmm2,%xmm5  
```
Intel's [optimisation reference](https://software.intel.com/sites/default/files/managed/9e/bc/64-ia-32-architectures-optimization-manual.pdf) tells that on both generations there is quite some performance penalty on mixing sse/avx128 in the dirty-upper-state:
![2021-03-08-13-47-21](https://user-images.githubusercontent.com/8302449/110330015-3104d180-8015-11eb-891c-14ef4f6ea105.png)
![2021-03-08-13-47-32](https://user-images.githubusercontent.com/8302449/110330041-35c98580-8015-11eb-8062-6bbd52883286.png)

According to the guide above, `xrstor` from the clean state should restore the clean upper state (and I see in gdb that upper registers are clean; in images ymmh_space is zeroed-out).
I'll look closer at this - maybe there is something with sigframe format that doesn't bring CPU to the clean upper-state.

Funny enough, with this diff:
```
diff --git a/compel/arch/x86/src/lib/include/uapi/asm/sigframe.h b/compel/arch/x86/sr>
index 486c0c8e03be..d63ade66fefd 100644
--- a/compel/arch/x86/src/lib/include/uapi/asm/sigframe.h
+++ b/compel/arch/x86/src/lib/include/uapi/asm/sigframe.h
@@ -210,6 +210,7 @@ void rt_sigframe_erase_sigset(struct rt_sigframe *sigframe)
 
 #define ARCH_RT_SIGRETURN(new_sp, rt_sigframe)                         \
 do {                                                                   \
+       asm volatile("vzeroupper" :::);                                 \
        if ((rt_sigframe)->is_native)                                   \
                ARCH_RT_SIGRETURN_NATIVE(new_sp);                       \
        else                                                            \
diff --git a/criu/pie/restorer.c b/criu/pie/restorer.c
index b3d7e2b5cd86..e9206cc67c47 100644
--- a/criu/pie/restorer.c
+++ b/criu/pie/restorer.c
@@ -1119,6 +1119,7 @@ unsigned int bootstrap_len = 0;
 
 void __export_unmap(void)
 {
+       asm volatile("vzeroupper" :::);
        sys_munmap(bootstrap_start, bootstrap_len - vdso_rt_size);
 }
 
```
I still see some difference:
```
# Baseline  Delta Abs  Shared Object           Symbol                             
# ........  .........  ......................  ...................................
#
    20.32%     +6.87%  libm-2.33.so            [.] __ieee754_log_fma
    65.82%     -6.27%  ep.C.x                  [.] MAIN__._omp_fn.1
```
(Probably, because we unmap restorer from the main thread, while sub-threads are just waiting).
We definitely need a zdtm test to check clean-upper-state after restore.

**Comment by 0x7f454c46** [comment] 2021-03-08 15:59
FWIW, clean up of upper state in all threads (see dirty hacking in https://github.com/0x7f454c46/criu/commit/4a67588dcb29642004ce22d841e7f87d2c74b352), removed any difference:
```
# Baseline  Delta Abs  Shared Object         Symbol                                  >
# ........  .........  ....................  ........................................>
#
               +0.34%  [kernel.kallsyms]     [k] 0xffffffff844058e4
    65.82%     -0.29%  ep.C.x                [.] MAIN__._omp_fn.1
    20.32%     -0.10%  libm-2.33.so          [.] __ieee754_log_fma
    11.14%     +0.05%  ep.C.x                [.] vranlc_
     0.86%     +0.05%  libm-2.33.so          [.] log@@GLIBC_2.29
     0.90%     -0.03%  ep.C.x                [.] log@plt
     0.01%     -0.01%  libgomp.so.1.0.0      [.] gomp_barrier_wait_end
```
(kernel.kallsyms is probably from criu-restore itself)

**Comment by 0x7f454c46** [comment] 2021-03-09 13:32
Ok, so https://github.com/0x7f454c46/criu/commit/d6fa479e4cdc94cd84182a2daf9deff7b22de288 seems to bring back the performance on the nasa benchmark. @planetA, could you try to apply it and see if that fixes your original issue?
(time to write some zdtm test for this annoyance)

**Comment by planetA** [comment] 2021-03-12 17:19
@0x7f454c46 Hi! Thanks a lot for your effort. This AVX stuff is outside my area of expertise :)

 I can't check it right now. Is it OK to close bug, and if reappears, I will reopen it?

**Comment by 0x7f454c46** [comment] 2021-03-12 19:40
@planetA, don't worry, I'll use this issue and close it with PR with a fix I've made.
Anyway, thanks for your report!

**Comment by Avijit009** [comment] 2021-10-01 06:29
@planetA Can I have a talk with you? I already mailed you. 

Sorry for this comment here.

**Comment by karthik-intel** [comment] 2023-02-27 22:50
At Intel, we saw this issue too and the fix here works: https://github.com/0x7f454c46/criu/commit/d6fa479e4cdc94cd84182a2daf9deff7b22de288
Does it make sense to mainstream the fix to the criu repo? 
Thank you!

**Closed** 2023-03-10 15:57 UTC
Labels: no-auto-close
