### ISSUE TITLE
Restore is not reliable

### ISSUE THREAD

**Issue by zl-wang** [checkpoint-restore/criu#1431] opened 2021-04-05 18:27 UTC
The same dump is used to restore for a few times continuously. I have observed: succeed twice and fail once, fail always, or with a different pattern.  The failing reason is usually like below:

```
(00.054781) pie: 33928: Restoring scheduler params 0.0.0
(00.054878) pie: 33928: Error (criu/pie/restorer.c:1832): Unable to create a thread: 33931
(00.054905) pie: 33928: Error (criu/pie/restorer.c:1972): Restorer fail 33928
(00.054906) pie: 33931: Error (criu/pie/restorer.c:586): Thread pid mismatch 33931/33930
(00.054933) Error (criu/cr-restore.c:2514): Restoring FAILED. 
```

**Comment by adrianreber** [comment] 2021-04-05 18:44
Assuming this is an older kernel (without clone3() set_tid) this is something which cannot be avoided easily.

To create a process with a certain PID (without clone3) CRIU writes to `/proc/sys/kernel/ns_last_pid` and the next process CRIU creates hopefully has the desired PID. From this point on new processes, unrelated to CRIU, will be created close in the range of the restored process and maybe the PID will be used by some other process. If you have a new enough kernel CRIU will use clone3 and only the restored processes will be using these PIDs. All other PIDs created will stay in the range the kernel is currently creating processes in.

But in the end this is always a problem you might see with CRIU. The best solution is to use a PID namespace to avoid PID collisions. Without PID namespaces PID collisions can always happen upon restore. clone3 can help a little bit to avoid PID collisions, but not totally.

I am closing this as this is by design and cannot be fixed. Try to use clone3 to reduce the probability of this error of use PID namespaces to avoid this error.

**Closed by adrianreber** 2021-04-05 18:44 UTC
