### ISSUE TITLE
crit unable to decode a byte

### ISSUE THREAD

**Issue by kpm4** [checkpoint-restore/criu#1484] opened 2021-05-23 16:08 UTC
hello.

I am trying to read the dump files with crit, so I dump a small process with:
$ criu dump -t 15719 --shell-job
Warn  (compel/arch/x86/src/lib/infect.c:358): Will restore 15719 with interrupted system call

so, now I am trying to read the dumped info with:

$ crit/crit x ./output/ fds
Traceback (most recent call last):
  File "/home/x/tools/criu/crit/crit", line 6, in <module>
    cli.main()
  File "/home/x/tools/criu/crit/pycriu/cli.py", line 430, in main
    opts["func"](opts)
  File "/home/x/tools/criu/crit/pycriu/cli.py", line 361, in explore
    explorers[opts['what']](opts)
  File "/home/x/tools/criu/crit/pycriu/cli.py", line 221, in explore_fds
    ps_img = pycriu.images.load(dinf(opts, 'pstree.img'))
  File "/home/x/tools/criu/crit/pycriu/images/images.py", line 588, in load
    m, handler = __rhandler(f)
  File "/home/x/tools/criu/crit/pycriu/images/images.py", line 562, in __rhandler
    img_magic, = struct.unpack('i', f.read(4))
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 13: invalid continuation byte

this is the pstree.img content:

$ xxd output/pstree.img | head
00000000: 1943 5654 3030 2750 0e00 0000 08e7 7a10  .CVT00'P......z.
00000010: 0018 e77a 208e 7a28 e77a                 ...z .z(.z

is this a known issue?

thanks

**Comment by adrianreber** [comment] 2021-05-23 16:18
Which version of CRIU? In the development branch there are many fixes for errors like this. So it could be fixed by now.

Also, does crit show output/fdinfo* work? Does that contain the data you are looking for? I guess your combination of parameters has not been verified to work since we switched to Python 3. But there are many other ways in which crit has been verified to work with Python 3.

**Comment by kpm4** [comment] 2021-05-23 16:52
I am using the last commit from main branch.

crit show and decode work. also on pstree.img (that seems to be the file with the issue)

$ crit/crit decode -i output/pstree.img 
{"magic": "PSTREE", "entries": [{"pid": 15719, "ppid": 0, "pgid": 15719, "sid": 15630, "threads": [15719]}]}

$ crit/crit show output/fdinfo*
{
    "magic": "FDINFO",
    "entries": [
        {
            "id": 5,
            "flags": 0,
            "type": "TTY",
            "fd": 0
        },
        {
            "id": 5,
            "flags": 0,
            "type": "TTY",
            "fd": 1
        },
        {
            "id": 5,
            "flags": 0,
            "type": "TTY",
            "fd": 2
        }
    ]
}

**Comment by adrianreber** [comment] 2021-05-23 17:11
Just tried it and I can confirm that is also needs fixing.

**Comment by rst0git** [comment] 2021-05-24 05:41
@kpm4 I opened a pull request to fix it.

**Closed** 2021-05-27 16:40 UTC
